trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  # Install Java (Option 1: JavaToolInstaller)
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'

  # Build & Run Rest Assured tests
  - script: mvn clean test -Dmaven.test.failure.ignore=true
    displayName: 'Run Rest Assured API tests'

  # Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/*.xml'
      testRunTitle: 'Rest Assured API Test Results'
    condition: succeededOrFailed()

  # Publish Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'test-reports'
      publishLocation: 'Container'
