trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_HUB_USERNAME: 'ayandakhaka1'
  IMAGE_NAME: 'restassured-tests'
  IMAGE_TAG: 'latest'
  TEST_REPORT_DIR: '$(Build.ArtifactStagingDirectory)/test-reports'

steps:

# 1️⃣ Checkout code
- task: Checkout@1

# 2️⃣ Login to Docker Hub
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHubConnection'

# 3️⃣ Build Docker image
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(DOCKER_HUB_USERNAME)/$(IMAGE_NAME)'
    command: build
    Dockerfile: '**/Dockerfile'
    tags: '$(IMAGE_TAG)'

# 4️⃣ Push Docker image
- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    repository: '$(DOCKER_HUB_USERNAME)/$(IMAGE_NAME)'
    command: push
    tags: '$(IMAGE_TAG)'

# 5️⃣ Run container and save test reports to mounted volume
- script: |
    mkdir -p $(TEST_REPORT_DIR)
    docker run --rm -v $(TEST_REPORT_DIR):/app/test-reports $(DOCKER_HUB_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG)
  displayName: 'Run Rest Assured tests'

# 6️⃣ Publish JUnit/Surefire test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(TEST_REPORT_DIR)/*.xml'
    testRunTitle: 'Rest Assured API Tests'
    mergeTestResults: true
    failTaskOnFailedTests: true
