trigger:
- main   # or your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'restassured-tests'
  dockerHubRepo: 'ayandakhaka1/restassured-tests'

steps:
# 1️⃣ Log in to Docker Hub
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHubServiceConnection'

# 2️⃣ Build Docker image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    repository: '$(dockerHubRepo)'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

# 3️⃣ Push to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image to Docker Hub'
  inputs:
    command: push
    repository: '$(dockerHubRepo)'
    tags: |
      latest

# 4️⃣ Run Tests inside Docker container and copy results out
- script: |
    echo "Running Rest Assured API Tests..."
    mkdir -p $(Build.SourcesDirectory)/test-results
    docker run --rm -v $(Build.SourcesDirectory)/test-results:/app/target/surefire-reports $(dockerHubRepo):latest
  displayName: 'Run Rest Assured Tests'

# 5️⃣ Publish Test Results to Azure DevOps UI
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '$(Build.SourcesDirectory)/test-results/*.xml'
    testRunTitle: 'Rest Assured API Tests'
