trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx1024m"

steps:
# 1️⃣ Install JDK 17
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureDownload'

# 2️⃣ Verify Java & Maven
- script: |
    java -version
    mvn -version
  displayName: 'Verify Java & Maven'

# 3️⃣ Run Maven tests
- script: mvn clean test
  displayName: 'Run Maven Tests'

# 4️⃣ Publish TestNG results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/*.xml'
    testRunTitle: 'TestNG Results'
    mergeTestResults: true
    failTaskOnFailedTests: true

# 5️⃣ Publish ExtentReports HTML as pipeline artifacts
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/extent-reports'   # Path where ExtentReports HTML is generated
    artifact: 'ExtentReports'
    publishLocation: 'pipeline'
