# Trigger pipeline on main branch
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx1024m"
  BUILD_NUMBER: $(Build.BuildNumber)
  GIT_COMMIT: $(Build.SourceVersion)

steps:

- script: mkdir -p $(HOME)/.m2/repository
  displayName: 'Ensure Maven cache directory exists'

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | pom.xml'
    path: $(HOME)/.m2/repository
    restoreKeys: |
      maven | "$(Agent.OS)"

- script: |
    echo "Java Version:"
    java -version
    echo "Maven Version:"
    mvn -version
  displayName: 'Verify Java & Maven'

- script: |
    mvn clean test -DsuiteXmlFile=testng.xml -T 2C -B -e \
      -DbuildNumber=$(BUILD_NUMBER) \
      -DgitCommit=$(GIT_COMMIT)
  displayName: 'Run Maven Tests with TestNG XML & Parallel Execution'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/*.xml'
    testRunTitle: 'TestNG Results'
    mergeTestResults: true
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/extent-reports'
    artifact: 'ExtentReports'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/surefire-reports'
    artifact: 'SurefireReports'
    publishLocation: 'pipeline'

- script: |
    echo "Flaky Test Summary:"
    grep -i "retry" target/surefire-reports/*.xml || echo "No flaky tests detected"
  displayName: 'Flaky Test Summary'

- script: |
    echo "Build Number: $(BUILD_NUMBER)"
    echo "Git Commit: $(GIT_COMMIT)"
    echo "Branch: $(Build.SourceBranch)"
  displayName: 'Log Build & Environment Info'
